<?php

/**
* @file
* Handles the creation and display of text/html files.
*/

/**
* Implements hook_theme
*/
function islandora_sp_text_html_theme($existing, $type, $theme, $path) {

    return [
        'islandora_sp_text_html_view' => [
            'template' => 'theme/islandora-sp-text-html-view',
        ],
    ];
}

/**
* Implements hook_islandora_required_objects().
*/
function islandora_sp_text_html_islandora_required_objects(IslandoraTuque $connection) {

    $modulePath = drupal_get_path('module', 'islandora_sp_text_html');

    // Content Model
    $contentModel         = $connection->repository->constructObject('islandora:sp_text_html');
    $contentModel->owner  = 'fedoraAdmin';
    $contentModel->label  = 'Islandora SP Text/HTML Content Model';
    $contentModel->models = 'fedora-system:ContentModel-3.0';

    // DS-COMPOSITE-MODEL Datastream
    $datastream           = $contentModel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
    $datastream->label    = 'DS-COMPOSITE-MODEL';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($modulePath . '/xml/islandora_sp_text_html_ds_composite_model.xml', false);
    $contentModel->ingestDatastream($datastream);

    // Collection
    $collection         = $connection->repository->constructObject('islandora:sp_text_html_collection');
    $collection->owner  = 'fedoraAdmin';
    $collection->label  = 'Text/HTML collection';
    $collection->models = 'islandora:collectionCModel';
    $collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

    // Collection Policy
    $datastream           = $collection->constructDatastream('COLLECTION_POLICY', 'X');
    $datastream->label    = 'Collection policy';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($modulePath . '/xml/islandora_sp_text_html_collection_policy.xml', false);
    $collection->ingestDatastream($datastream);

    return [

        'islandora_sp_text_html' => [

            'title'   => 'Islandora SP Text/HTML',
            'objects' => [

                $contentModel,
                $collection,
            ],
        ],
    ];
}

/**
* Implements hook_CMODEL_PID_islandora_view_object().
*/
function islandora_sp_text_html_islandora_sp_text_html_islandora_view_object($object, $page_number, $page_size) {

    $datastream = $filteredContent = $object->getDatastream('OBJ');

    if ($datastream->mimetype === 'text/html') {
        $content = $datastream->content;
        // since drupal filtered_html does not filter text between style tags, we'll do that first
        $filteredContent = preg_replace('@<style[^>]*?>.*?</style>@siu', '', $content);
        $filteredContent = check_markup($filteredContent, 'filtered_html');
    } elseif ($datastream->mimetype === 'text/plain') {
        $filteredContent = check_markup($datastream->content, 'plain_text');
    } else {
        $filteredContent = '';
    }

    return theme('islandora_sp_text_html_view', [
        'content' => $filteredContent,
    ]);
}

function islandora_sp_text_html_islandora_sp_text_html_islandora_ingest_steps() {

    return [

        'islandora_sp_text_html' => [

            'weight'  => 10,
            'type'    => 'form',
            'form_id' => 'islandora_sp_text_html_text_html_upload',
            'module'  => 'islandora_sp_text_html',
            'file'    => 'includes/text_html_upload.form.inc',
        ],
    ];
}
